export const TRANSLATIONS = {
    'id': {
        'btn-inv': '🎒 Tas',
        'btn-save': '💾 Simpan',
        'btn-load': '📂 Muat',
        'btn-reset': '❌ Reset',
        'btn-settings': '⚙️ API Key',
        'header-inv': 'Tas Penyimpanan',
        'btn-craft-mode': 'Mode Crafting: ',
        'btn-craft-action': 'GABUNGKAN',
        'txt-close-inv': '▲ Tutup Tas ▲',
        'input-placeholder': 'Tulis aksi...',
        'btn-go': 'Kirim',
        'txt-skill-check': 'CEK SKILL:',
        'txt-tap-dice': 'Ketuk dadu',
        'btn-use': 'Gunakan',
        'btn-view': 'Lihat',
        'btn-drop': 'Buang',
        'btn-cancel': 'Batal',
        'screen-setup-title': 'SETUP DUNIA',
        'header-genre': '1. GAYA BERMAIN (MAX 3)',
        'header-theme': '2. TEMA DUNIA (MAX 3)',
        'btn-next-setup': 'LANJUT ->',
        'screen-char-title': 'PEMBUATAN KARAKTER',
        'lbl-char-name': 'Nama Karakter',
        'btn-start-game': 'Mulai Petualangan',
        'modal-api-title': '🔑 Pengaturan API Key',
        'modal-api-desc': 'Masukkan API Key Google Gemini Anda untuk bermain. Key akan disimpan di browser ini.',
        'lbl-api-key': 'Google Gemini API Key',
        'btn-save-api': 'Simpan',
        'link-get-key': 'Dapatkan API Key di sini',
        'btn-back-setup': '← KEMBALI',
        'loading-form': 'Sedang menyusun formulir karakter...',
        'status-hp': 'HP',
        'inv-empty': 'Kosong',
        'craft-slot-1': 'Pilih Item 1',
        'craft-slot-2': 'Pilih Item 2'
    },
    'en': {
        'btn-inv': '🎒 Bag',
        'btn-save': '💾 Save',
        'btn-load': '📂 Load',
        'btn-reset': '❌ Reset',
        'btn-settings': '⚙️ API Key',
        'header-inv': 'Inventory',
        'btn-craft-mode': 'Crafting Mode: ',
        'btn-craft-action': 'COMBINE',
        'txt-close-inv': '▲ Close Bag ▲',
        'input-placeholder': 'Type action...',
        'btn-go': 'Go',
        'txt-skill-check': 'SKILL CHECK:',
        'txt-tap-dice': 'Tap dice',
        'btn-use': 'Use',
        'btn-view': 'Inspect',
        'btn-drop': 'Drop',
        'btn-cancel': 'Cancel',
        'screen-setup-title': 'WORLD SETUP',
        'header-genre': '1. GAMEPLAY STYLE (MAX 3)',
        'header-theme': '2. WORLD THEME (MAX 3)',
        'btn-next-setup': 'NEXT ->',
        'screen-char-title': 'CHARACTER CREATION',
        'lbl-char-name': 'Character Name',
        'btn-start-game': 'Start Adventure',
        'modal-api-title': '🔑 API Key Settings',
        'modal-api-desc': 'Enter your Google Gemini API Key to play. It will be stored in this browser.',
        'lbl-api-key': 'Google Gemini API Key',
        'btn-save-api': 'Save',
        'link-get-key': 'Get API Key here',
        'btn-back-setup': '← BACK',
        'loading-form': 'Constructing character form...',
        'status-hp': 'HP',
        'inv-empty': 'Empty',
        'craft-slot-1': 'Select Item 1',
        'craft-slot-2': 'Select Item 2'
    }
};
